import { chromium } from "playwright";
const BASE_URL = "http://localhost:3000";
const OUT_DIR = "docs/guides-utilisation/pressing/screenshots/pressing";
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 320, height: 700 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto(`${BASE_URL}/login`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(1500);
await page.locator('input[name="login"]').fill("admin");
await page.locator('input[name="motDePasse"]').fill("motdepasse");
await page.getByRole("button", { name: "Se connecter" }).click();
await page.waitForURL("**/home", { timeout: 20000 });
await page.waitForTimeout(2000);
await page.goto(`${BASE_URL}/pressing/commandes`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(2500);
const lien = page.locator("table tbody tr td a").first();
await lien.click();
await page.waitForURL("**/pressing/commandes/**", { timeout: 15000 });
await page.waitForTimeout(2500);
await page.screenshot({ path: `${OUT_DIR}/14-fiche-mobile.png`, fullPage: true });
console.log("📸 14-fiche-mobile");
await ctx.close(); await browser.close();
