/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedEnCoursRouteImport } from './routes/_authenticated/en-cours'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedRapportsIndexRouteImport } from './routes/_authenticated/rapports/index'
import { Route as AuthenticatedAdminJournalIndexRouteImport } from './routes/_authenticated/admin/journal/index'
import { Route as AuthenticatedAdminParametresIndexRouteImport } from './routes/_authenticated/admin/parametres/index'
import { Route as AuthenticatedAdminRolesIndexRouteImport } from './routes/_authenticated/admin/roles/index'
import { Route as AuthenticatedAdminSauvegardesIndexRouteImport } from './routes/_authenticated/admin/sauvegardes/index'
import { Route as AuthenticatedAdminUtilisateursIndexRouteImport } from './routes/_authenticated/admin/utilisateurs/index'
import { Route as AuthenticatedClientClientsIndexRouteImport } from './routes/_authenticated/client/clients/index'
import { Route as AuthenticatedClientClientsIdRouteImport } from './routes/_authenticated/client/clients/$id'
import { Route as AuthenticatedFacturationFacturesIndexRouteImport } from './routes/_authenticated/facturation/factures/index'
import { Route as AuthenticatedFacturationFacturesIdRouteImport } from './routes/_authenticated/facturation/factures/$id'
import { Route as AuthenticatedFacturationPrestationsIndexRouteImport } from './routes/_authenticated/facturation/prestations/index'
import { Route as AuthenticatedFinancesCaissesIndexRouteImport } from './routes/_authenticated/finances/caisses/index'
import { Route as AuthenticatedFinancesCategoriesDepensesIndexRouteImport } from './routes/_authenticated/finances/categories-depenses/index'
import { Route as AuthenticatedFinancesDepensesIndexRouteImport } from './routes/_authenticated/finances/depenses/index'
import { Route as AuthenticatedFinancesEncaissementsIndexRouteImport } from './routes/_authenticated/finances/encaissements/index'
import { Route as AuthenticatedFinancesImpayesIndexRouteImport } from './routes/_authenticated/finances/impayes/index'
import { Route as AuthenticatedFinancesMoyensPaiementIndexRouteImport } from './routes/_authenticated/finances/moyens-paiement/index'
import { Route as AuthenticatedFinancesRevenusUtilisateurIndexRouteImport } from './routes/_authenticated/finances/revenus-utilisateur/index'
import { Route as AuthenticatedFinancesTableauDeBordIndexRouteImport } from './routes/_authenticated/finances/tableau-de-bord/index'
import { Route as AuthenticatedMarchandiseCategoriesProduitsIndexRouteImport } from './routes/_authenticated/marchandise/categories-produits/index'
import { Route as AuthenticatedMarchandiseMouvementsIndexRouteImport } from './routes/_authenticated/marchandise/mouvements/index'
import { Route as AuthenticatedMarchandiseProduitsIndexRouteImport } from './routes/_authenticated/marchandise/produits/index'
import { Route as AuthenticatedMarchandiseStatistiquesIndexRouteImport } from './routes/_authenticated/marchandise/statistiques/index'
import { Route as AuthenticatedMarchandiseVentesIndexRouteImport } from './routes/_authenticated/marchandise/ventes/index'
import { Route as AuthenticatedPressingCommandesIndexRouteImport } from './routes/_authenticated/pressing/commandes/index'
import { Route as AuthenticatedPressingCommandesIdRouteImport } from './routes/_authenticated/pressing/commandes/$id'
import { Route as AuthenticatedRapportsActivitesCodeRouteImport } from './routes/_authenticated/rapports/activites/$code'
import { Route as AuthenticatedRapportsFinancierIndexRouteImport } from './routes/_authenticated/rapports/financier/index'
import { Route as AuthenticatedRapportsRhIndexRouteImport } from './routes/_authenticated/rapports/rh/index'
import { Route as AuthenticatedRapportsSyntheseGlobaleIndexRouteImport } from './routes/_authenticated/rapports/synthese-globale/index'
import { Route as AuthenticatedResidenceAbonnementsIndexRouteImport } from './routes/_authenticated/residence/abonnements/index'
import { Route as AuthenticatedResidenceBatimentsIndexRouteImport } from './routes/_authenticated/residence/batiments/index'
import { Route as AuthenticatedResidenceCategoriesChargesIndexRouteImport } from './routes/_authenticated/residence/categories-charges/index'
import { Route as AuthenticatedResidenceChargesIndexRouteImport } from './routes/_authenticated/residence/charges/index'
import { Route as AuthenticatedResidenceContratsIndexRouteImport } from './routes/_authenticated/residence/contrats/index'
import { Route as AuthenticatedResidenceContratsIdRouteImport } from './routes/_authenticated/residence/contrats/$id'
import { Route as AuthenticatedResidenceEcheancesIndexRouteImport } from './routes/_authenticated/residence/echeances/index'
import { Route as AuthenticatedResidenceLogementsIndexRouteImport } from './routes/_authenticated/residence/logements/index'
import { Route as AuthenticatedResidenceLogementsIdRouteImport } from './routes/_authenticated/residence/logements/$id'
import { Route as AuthenticatedResidencePortailIndexRouteImport } from './routes/_authenticated/residence/portail/index'
import { Route as AuthenticatedResidenceSejoursCourtsIndexRouteImport } from './routes/_authenticated/residence/sejours-courts/index'
import { Route as AuthenticatedResidenceSejoursCourtsIdRouteImport } from './routes/_authenticated/residence/sejours-courts/$id'
import { Route as AuthenticatedRestaurantCommandesIndexRouteImport } from './routes/_authenticated/restaurant/commandes/index'
import { Route as AuthenticatedRestaurantPlatsIndexRouteImport } from './routes/_authenticated/restaurant/plats/index'
import { Route as AuthenticatedRestaurantStatistiquesIndexRouteImport } from './routes/_authenticated/restaurant/statistiques/index'
import { Route as AuthenticatedRhBulletinsIndexRouteImport } from './routes/_authenticated/rh/bulletins/index'
import { Route as AuthenticatedRhBulletinsIdRouteImport } from './routes/_authenticated/rh/bulletins/$id'
import { Route as AuthenticatedRhComptesIndexRouteImport } from './routes/_authenticated/rh/comptes/index'
import { Route as AuthenticatedRhEmployesIndexRouteImport } from './routes/_authenticated/rh/employes/index'
import { Route as AuthenticatedRhEmployesIdRouteImport } from './routes/_authenticated/rh/employes/$id'
import { Route as AuthenticatedRhPointageIndexRouteImport } from './routes/_authenticated/rh/pointage/index'
import { Route as AuthenticatedSalleFeteCalendrierIndexRouteImport } from './routes/_authenticated/salle-fete/calendrier/index'
import { Route as AuthenticatedSalleFeteReservationsIndexRouteImport } from './routes/_authenticated/salle-fete/reservations/index'
import { Route as AuthenticatedSalleFeteReservationsIdRouteImport } from './routes/_authenticated/salle-fete/reservations/$id'
import { Route as AuthenticatedFinancesCaissesIdDashboardRouteImport } from './routes/_authenticated/finances/caisses/$id/dashboard'
import { Route as AuthenticatedFinancesCaissierIdDashboardRouteImport } from './routes/_authenticated/finances/caissier/$id/dashboard'
import { Route as AuthenticatedFinancesCaissierIdTiragesRouteImport } from './routes/_authenticated/finances/caissier/$id/tirages'
import { Route as AuthenticatedResidencePortailCautionIndexRouteImport } from './routes/_authenticated/residence/portail/caution/index'
import { Route as AuthenticatedResidencePortailEcheancesIndexRouteImport } from './routes/_authenticated/residence/portail/echeances/index'
import { Route as AuthenticatedResidencePortailPaiementsIndexRouteImport } from './routes/_authenticated/residence/portail/paiements/index'
import { Route as AuthenticatedRhPointageConsultationIndexRouteImport } from './routes/_authenticated/rh/pointage/consultation/index'
import { Route as AuthenticatedAdminRolesIdPermissionsIndexRouteImport } from './routes/_authenticated/admin/roles/$id/permissions/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEnCoursRoute = AuthenticatedEnCoursRouteImport.update({
  id: '/en-cours',
  path: '/en-cours',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRapportsIndexRoute =
  AuthenticatedRapportsIndexRouteImport.update({
    id: '/rapports/',
    path: '/rapports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminJournalIndexRoute =
  AuthenticatedAdminJournalIndexRouteImport.update({
    id: '/admin/journal/',
    path: '/admin/journal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminParametresIndexRoute =
  AuthenticatedAdminParametresIndexRouteImport.update({
    id: '/admin/parametres/',
    path: '/admin/parametres/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexRouteImport.update({
    id: '/admin/roles/',
    path: '/admin/roles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSauvegardesIndexRoute =
  AuthenticatedAdminSauvegardesIndexRouteImport.update({
    id: '/admin/sauvegardes/',
    path: '/admin/sauvegardes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUtilisateursIndexRoute =
  AuthenticatedAdminUtilisateursIndexRouteImport.update({
    id: '/admin/utilisateurs/',
    path: '/admin/utilisateurs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientClientsIndexRoute =
  AuthenticatedClientClientsIndexRouteImport.update({
    id: '/client/clients/',
    path: '/client/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientClientsIdRoute =
  AuthenticatedClientClientsIdRouteImport.update({
    id: '/client/clients/$id',
    path: '/client/clients/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturationFacturesIndexRoute =
  AuthenticatedFacturationFacturesIndexRouteImport.update({
    id: '/facturation/factures/',
    path: '/facturation/factures/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturationFacturesIdRoute =
  AuthenticatedFacturationFacturesIdRouteImport.update({
    id: '/facturation/factures/$id',
    path: '/facturation/factures/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturationPrestationsIndexRoute =
  AuthenticatedFacturationPrestationsIndexRouteImport.update({
    id: '/facturation/prestations/',
    path: '/facturation/prestations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesCaissesIndexRoute =
  AuthenticatedFinancesCaissesIndexRouteImport.update({
    id: '/finances/caisses/',
    path: '/finances/caisses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesCategoriesDepensesIndexRoute =
  AuthenticatedFinancesCategoriesDepensesIndexRouteImport.update({
    id: '/finances/categories-depenses/',
    path: '/finances/categories-depenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesDepensesIndexRoute =
  AuthenticatedFinancesDepensesIndexRouteImport.update({
    id: '/finances/depenses/',
    path: '/finances/depenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesEncaissementsIndexRoute =
  AuthenticatedFinancesEncaissementsIndexRouteImport.update({
    id: '/finances/encaissements/',
    path: '/finances/encaissements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesImpayesIndexRoute =
  AuthenticatedFinancesImpayesIndexRouteImport.update({
    id: '/finances/impayes/',
    path: '/finances/impayes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesMoyensPaiementIndexRoute =
  AuthenticatedFinancesMoyensPaiementIndexRouteImport.update({
    id: '/finances/moyens-paiement/',
    path: '/finances/moyens-paiement/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesRevenusUtilisateurIndexRoute =
  AuthenticatedFinancesRevenusUtilisateurIndexRouteImport.update({
    id: '/finances/revenus-utilisateur/',
    path: '/finances/revenus-utilisateur/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesTableauDeBordIndexRoute =
  AuthenticatedFinancesTableauDeBordIndexRouteImport.update({
    id: '/finances/tableau-de-bord/',
    path: '/finances/tableau-de-bord/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarchandiseCategoriesProduitsIndexRoute =
  AuthenticatedMarchandiseCategoriesProduitsIndexRouteImport.update({
    id: '/marchandise/categories-produits/',
    path: '/marchandise/categories-produits/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarchandiseMouvementsIndexRoute =
  AuthenticatedMarchandiseMouvementsIndexRouteImport.update({
    id: '/marchandise/mouvements/',
    path: '/marchandise/mouvements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarchandiseProduitsIndexRoute =
  AuthenticatedMarchandiseProduitsIndexRouteImport.update({
    id: '/marchandise/produits/',
    path: '/marchandise/produits/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarchandiseStatistiquesIndexRoute =
  AuthenticatedMarchandiseStatistiquesIndexRouteImport.update({
    id: '/marchandise/statistiques/',
    path: '/marchandise/statistiques/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarchandiseVentesIndexRoute =
  AuthenticatedMarchandiseVentesIndexRouteImport.update({
    id: '/marchandise/ventes/',
    path: '/marchandise/ventes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPressingCommandesIndexRoute =
  AuthenticatedPressingCommandesIndexRouteImport.update({
    id: '/pressing/commandes/',
    path: '/pressing/commandes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPressingCommandesIdRoute =
  AuthenticatedPressingCommandesIdRouteImport.update({
    id: '/pressing/commandes/$id',
    path: '/pressing/commandes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRapportsActivitesCodeRoute =
  AuthenticatedRapportsActivitesCodeRouteImport.update({
    id: '/rapports/activites/$code',
    path: '/rapports/activites/$code',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRapportsFinancierIndexRoute =
  AuthenticatedRapportsFinancierIndexRouteImport.update({
    id: '/rapports/financier/',
    path: '/rapports/financier/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRapportsRhIndexRoute =
  AuthenticatedRapportsRhIndexRouteImport.update({
    id: '/rapports/rh/',
    path: '/rapports/rh/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRapportsSyntheseGlobaleIndexRoute =
  AuthenticatedRapportsSyntheseGlobaleIndexRouteImport.update({
    id: '/rapports/synthese-globale/',
    path: '/rapports/synthese-globale/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceAbonnementsIndexRoute =
  AuthenticatedResidenceAbonnementsIndexRouteImport.update({
    id: '/residence/abonnements/',
    path: '/residence/abonnements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceBatimentsIndexRoute =
  AuthenticatedResidenceBatimentsIndexRouteImport.update({
    id: '/residence/batiments/',
    path: '/residence/batiments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceCategoriesChargesIndexRoute =
  AuthenticatedResidenceCategoriesChargesIndexRouteImport.update({
    id: '/residence/categories-charges/',
    path: '/residence/categories-charges/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceChargesIndexRoute =
  AuthenticatedResidenceChargesIndexRouteImport.update({
    id: '/residence/charges/',
    path: '/residence/charges/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceContratsIndexRoute =
  AuthenticatedResidenceContratsIndexRouteImport.update({
    id: '/residence/contrats/',
    path: '/residence/contrats/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceContratsIdRoute =
  AuthenticatedResidenceContratsIdRouteImport.update({
    id: '/residence/contrats/$id',
    path: '/residence/contrats/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceEcheancesIndexRoute =
  AuthenticatedResidenceEcheancesIndexRouteImport.update({
    id: '/residence/echeances/',
    path: '/residence/echeances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceLogementsIndexRoute =
  AuthenticatedResidenceLogementsIndexRouteImport.update({
    id: '/residence/logements/',
    path: '/residence/logements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceLogementsIdRoute =
  AuthenticatedResidenceLogementsIdRouteImport.update({
    id: '/residence/logements/$id',
    path: '/residence/logements/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidencePortailIndexRoute =
  AuthenticatedResidencePortailIndexRouteImport.update({
    id: '/residence/portail/',
    path: '/residence/portail/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceSejoursCourtsIndexRoute =
  AuthenticatedResidenceSejoursCourtsIndexRouteImport.update({
    id: '/residence/sejours-courts/',
    path: '/residence/sejours-courts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidenceSejoursCourtsIdRoute =
  AuthenticatedResidenceSejoursCourtsIdRouteImport.update({
    id: '/residence/sejours-courts/$id',
    path: '/residence/sejours-courts/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRestaurantCommandesIndexRoute =
  AuthenticatedRestaurantCommandesIndexRouteImport.update({
    id: '/restaurant/commandes/',
    path: '/restaurant/commandes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRestaurantPlatsIndexRoute =
  AuthenticatedRestaurantPlatsIndexRouteImport.update({
    id: '/restaurant/plats/',
    path: '/restaurant/plats/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRestaurantStatistiquesIndexRoute =
  AuthenticatedRestaurantStatistiquesIndexRouteImport.update({
    id: '/restaurant/statistiques/',
    path: '/restaurant/statistiques/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRhBulletinsIndexRoute =
  AuthenticatedRhBulletinsIndexRouteImport.update({
    id: '/rh/bulletins/',
    path: '/rh/bulletins/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRhBulletinsIdRoute =
  AuthenticatedRhBulletinsIdRouteImport.update({
    id: '/rh/bulletins/$id',
    path: '/rh/bulletins/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRhComptesIndexRoute =
  AuthenticatedRhComptesIndexRouteImport.update({
    id: '/rh/comptes/',
    path: '/rh/comptes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRhEmployesIndexRoute =
  AuthenticatedRhEmployesIndexRouteImport.update({
    id: '/rh/employes/',
    path: '/rh/employes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRhEmployesIdRoute =
  AuthenticatedRhEmployesIdRouteImport.update({
    id: '/rh/employes/$id',
    path: '/rh/employes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRhPointageIndexRoute =
  AuthenticatedRhPointageIndexRouteImport.update({
    id: '/rh/pointage/',
    path: '/rh/pointage/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalleFeteCalendrierIndexRoute =
  AuthenticatedSalleFeteCalendrierIndexRouteImport.update({
    id: '/salle-fete/calendrier/',
    path: '/salle-fete/calendrier/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalleFeteReservationsIndexRoute =
  AuthenticatedSalleFeteReservationsIndexRouteImport.update({
    id: '/salle-fete/reservations/',
    path: '/salle-fete/reservations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalleFeteReservationsIdRoute =
  AuthenticatedSalleFeteReservationsIdRouteImport.update({
    id: '/salle-fete/reservations/$id',
    path: '/salle-fete/reservations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesCaissesIdDashboardRoute =
  AuthenticatedFinancesCaissesIdDashboardRouteImport.update({
    id: '/finances/caisses/$id/dashboard',
    path: '/finances/caisses/$id/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesCaissierIdDashboardRoute =
  AuthenticatedFinancesCaissierIdDashboardRouteImport.update({
    id: '/finances/caissier/$id/dashboard',
    path: '/finances/caissier/$id/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesCaissierIdTiragesRoute =
  AuthenticatedFinancesCaissierIdTiragesRouteImport.update({
    id: '/finances/caissier/$id/tirages',
    path: '/finances/caissier/$id/tirages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidencePortailCautionIndexRoute =
  AuthenticatedResidencePortailCautionIndexRouteImport.update({
    id: '/residence/portail/caution/',
    path: '/residence/portail/caution/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidencePortailEcheancesIndexRoute =
  AuthenticatedResidencePortailEcheancesIndexRouteImport.update({
    id: '/residence/portail/echeances/',
    path: '/residence/portail/echeances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidencePortailPaiementsIndexRoute =
  AuthenticatedResidencePortailPaiementsIndexRouteImport.update({
    id: '/residence/portail/paiements/',
    path: '/residence/portail/paiements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRhPointageConsultationIndexRoute =
  AuthenticatedRhPointageConsultationIndexRouteImport.update({
    id: '/rh/pointage/consultation/',
    path: '/rh/pointage/consultation/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesIdPermissionsIndexRoute =
  AuthenticatedAdminRolesIdPermissionsIndexRouteImport.update({
    id: '/admin/roles/$id/permissions/',
    path: '/admin/roles/$id/permissions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/en-cours': typeof AuthenticatedEnCoursRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/rapports/': typeof AuthenticatedRapportsIndexRoute
  '/client/clients/$id': typeof AuthenticatedClientClientsIdRoute
  '/facturation/factures/$id': typeof AuthenticatedFacturationFacturesIdRoute
  '/pressing/commandes/$id': typeof AuthenticatedPressingCommandesIdRoute
  '/rapports/activites/$code': typeof AuthenticatedRapportsActivitesCodeRoute
  '/residence/contrats/$id': typeof AuthenticatedResidenceContratsIdRoute
  '/residence/logements/$id': typeof AuthenticatedResidenceLogementsIdRoute
  '/residence/sejours-courts/$id': typeof AuthenticatedResidenceSejoursCourtsIdRoute
  '/rh/bulletins/$id': typeof AuthenticatedRhBulletinsIdRoute
  '/rh/employes/$id': typeof AuthenticatedRhEmployesIdRoute
  '/salle-fete/reservations/$id': typeof AuthenticatedSalleFeteReservationsIdRoute
  '/admin/journal/': typeof AuthenticatedAdminJournalIndexRoute
  '/admin/parametres/': typeof AuthenticatedAdminParametresIndexRoute
  '/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/sauvegardes/': typeof AuthenticatedAdminSauvegardesIndexRoute
  '/admin/utilisateurs/': typeof AuthenticatedAdminUtilisateursIndexRoute
  '/client/clients/': typeof AuthenticatedClientClientsIndexRoute
  '/facturation/factures/': typeof AuthenticatedFacturationFacturesIndexRoute
  '/facturation/prestations/': typeof AuthenticatedFacturationPrestationsIndexRoute
  '/finances/caisses/': typeof AuthenticatedFinancesCaissesIndexRoute
  '/finances/categories-depenses/': typeof AuthenticatedFinancesCategoriesDepensesIndexRoute
  '/finances/depenses/': typeof AuthenticatedFinancesDepensesIndexRoute
  '/finances/encaissements/': typeof AuthenticatedFinancesEncaissementsIndexRoute
  '/finances/impayes/': typeof AuthenticatedFinancesImpayesIndexRoute
  '/finances/moyens-paiement/': typeof AuthenticatedFinancesMoyensPaiementIndexRoute
  '/finances/revenus-utilisateur/': typeof AuthenticatedFinancesRevenusUtilisateurIndexRoute
  '/finances/tableau-de-bord/': typeof AuthenticatedFinancesTableauDeBordIndexRoute
  '/marchandise/categories-produits/': typeof AuthenticatedMarchandiseCategoriesProduitsIndexRoute
  '/marchandise/mouvements/': typeof AuthenticatedMarchandiseMouvementsIndexRoute
  '/marchandise/produits/': typeof AuthenticatedMarchandiseProduitsIndexRoute
  '/marchandise/statistiques/': typeof AuthenticatedMarchandiseStatistiquesIndexRoute
  '/marchandise/ventes/': typeof AuthenticatedMarchandiseVentesIndexRoute
  '/pressing/commandes/': typeof AuthenticatedPressingCommandesIndexRoute
  '/rapports/financier/': typeof AuthenticatedRapportsFinancierIndexRoute
  '/rapports/rh/': typeof AuthenticatedRapportsRhIndexRoute
  '/rapports/synthese-globale/': typeof AuthenticatedRapportsSyntheseGlobaleIndexRoute
  '/residence/abonnements/': typeof AuthenticatedResidenceAbonnementsIndexRoute
  '/residence/batiments/': typeof AuthenticatedResidenceBatimentsIndexRoute
  '/residence/categories-charges/': typeof AuthenticatedResidenceCategoriesChargesIndexRoute
  '/residence/charges/': typeof AuthenticatedResidenceChargesIndexRoute
  '/residence/contrats/': typeof AuthenticatedResidenceContratsIndexRoute
  '/residence/echeances/': typeof AuthenticatedResidenceEcheancesIndexRoute
  '/residence/logements/': typeof AuthenticatedResidenceLogementsIndexRoute
  '/residence/portail/': typeof AuthenticatedResidencePortailIndexRoute
  '/residence/sejours-courts/': typeof AuthenticatedResidenceSejoursCourtsIndexRoute
  '/restaurant/commandes/': typeof AuthenticatedRestaurantCommandesIndexRoute
  '/restaurant/plats/': typeof AuthenticatedRestaurantPlatsIndexRoute
  '/restaurant/statistiques/': typeof AuthenticatedRestaurantStatistiquesIndexRoute
  '/rh/bulletins/': typeof AuthenticatedRhBulletinsIndexRoute
  '/rh/comptes/': typeof AuthenticatedRhComptesIndexRoute
  '/rh/employes/': typeof AuthenticatedRhEmployesIndexRoute
  '/rh/pointage/': typeof AuthenticatedRhPointageIndexRoute
  '/salle-fete/calendrier/': typeof AuthenticatedSalleFeteCalendrierIndexRoute
  '/salle-fete/reservations/': typeof AuthenticatedSalleFeteReservationsIndexRoute
  '/finances/caisses/$id/dashboard': typeof AuthenticatedFinancesCaissesIdDashboardRoute
  '/finances/caissier/$id/dashboard': typeof AuthenticatedFinancesCaissierIdDashboardRoute
  '/finances/caissier/$id/tirages': typeof AuthenticatedFinancesCaissierIdTiragesRoute
  '/residence/portail/caution/': typeof AuthenticatedResidencePortailCautionIndexRoute
  '/residence/portail/echeances/': typeof AuthenticatedResidencePortailEcheancesIndexRoute
  '/residence/portail/paiements/': typeof AuthenticatedResidencePortailPaiementsIndexRoute
  '/rh/pointage/consultation/': typeof AuthenticatedRhPointageConsultationIndexRoute
  '/admin/roles/$id/permissions/': typeof AuthenticatedAdminRolesIdPermissionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/en-cours': typeof AuthenticatedEnCoursRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/rapports': typeof AuthenticatedRapportsIndexRoute
  '/client/clients/$id': typeof AuthenticatedClientClientsIdRoute
  '/facturation/factures/$id': typeof AuthenticatedFacturationFacturesIdRoute
  '/pressing/commandes/$id': typeof AuthenticatedPressingCommandesIdRoute
  '/rapports/activites/$code': typeof AuthenticatedRapportsActivitesCodeRoute
  '/residence/contrats/$id': typeof AuthenticatedResidenceContratsIdRoute
  '/residence/logements/$id': typeof AuthenticatedResidenceLogementsIdRoute
  '/residence/sejours-courts/$id': typeof AuthenticatedResidenceSejoursCourtsIdRoute
  '/rh/bulletins/$id': typeof AuthenticatedRhBulletinsIdRoute
  '/rh/employes/$id': typeof AuthenticatedRhEmployesIdRoute
  '/salle-fete/reservations/$id': typeof AuthenticatedSalleFeteReservationsIdRoute
  '/admin/journal': typeof AuthenticatedAdminJournalIndexRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/sauvegardes': typeof AuthenticatedAdminSauvegardesIndexRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursIndexRoute
  '/client/clients': typeof AuthenticatedClientClientsIndexRoute
  '/facturation/factures': typeof AuthenticatedFacturationFacturesIndexRoute
  '/facturation/prestations': typeof AuthenticatedFacturationPrestationsIndexRoute
  '/finances/caisses': typeof AuthenticatedFinancesCaissesIndexRoute
  '/finances/categories-depenses': typeof AuthenticatedFinancesCategoriesDepensesIndexRoute
  '/finances/depenses': typeof AuthenticatedFinancesDepensesIndexRoute
  '/finances/encaissements': typeof AuthenticatedFinancesEncaissementsIndexRoute
  '/finances/impayes': typeof AuthenticatedFinancesImpayesIndexRoute
  '/finances/moyens-paiement': typeof AuthenticatedFinancesMoyensPaiementIndexRoute
  '/finances/revenus-utilisateur': typeof AuthenticatedFinancesRevenusUtilisateurIndexRoute
  '/finances/tableau-de-bord': typeof AuthenticatedFinancesTableauDeBordIndexRoute
  '/marchandise/categories-produits': typeof AuthenticatedMarchandiseCategoriesProduitsIndexRoute
  '/marchandise/mouvements': typeof AuthenticatedMarchandiseMouvementsIndexRoute
  '/marchandise/produits': typeof AuthenticatedMarchandiseProduitsIndexRoute
  '/marchandise/statistiques': typeof AuthenticatedMarchandiseStatistiquesIndexRoute
  '/marchandise/ventes': typeof AuthenticatedMarchandiseVentesIndexRoute
  '/pressing/commandes': typeof AuthenticatedPressingCommandesIndexRoute
  '/rapports/financier': typeof AuthenticatedRapportsFinancierIndexRoute
  '/rapports/rh': typeof AuthenticatedRapportsRhIndexRoute
  '/rapports/synthese-globale': typeof AuthenticatedRapportsSyntheseGlobaleIndexRoute
  '/residence/abonnements': typeof AuthenticatedResidenceAbonnementsIndexRoute
  '/residence/batiments': typeof AuthenticatedResidenceBatimentsIndexRoute
  '/residence/categories-charges': typeof AuthenticatedResidenceCategoriesChargesIndexRoute
  '/residence/charges': typeof AuthenticatedResidenceChargesIndexRoute
  '/residence/contrats': typeof AuthenticatedResidenceContratsIndexRoute
  '/residence/echeances': typeof AuthenticatedResidenceEcheancesIndexRoute
  '/residence/logements': typeof AuthenticatedResidenceLogementsIndexRoute
  '/residence/portail': typeof AuthenticatedResidencePortailIndexRoute
  '/residence/sejours-courts': typeof AuthenticatedResidenceSejoursCourtsIndexRoute
  '/restaurant/commandes': typeof AuthenticatedRestaurantCommandesIndexRoute
  '/restaurant/plats': typeof AuthenticatedRestaurantPlatsIndexRoute
  '/restaurant/statistiques': typeof AuthenticatedRestaurantStatistiquesIndexRoute
  '/rh/bulletins': typeof AuthenticatedRhBulletinsIndexRoute
  '/rh/comptes': typeof AuthenticatedRhComptesIndexRoute
  '/rh/employes': typeof AuthenticatedRhEmployesIndexRoute
  '/rh/pointage': typeof AuthenticatedRhPointageIndexRoute
  '/salle-fete/calendrier': typeof AuthenticatedSalleFeteCalendrierIndexRoute
  '/salle-fete/reservations': typeof AuthenticatedSalleFeteReservationsIndexRoute
  '/finances/caisses/$id/dashboard': typeof AuthenticatedFinancesCaissesIdDashboardRoute
  '/finances/caissier/$id/dashboard': typeof AuthenticatedFinancesCaissierIdDashboardRoute
  '/finances/caissier/$id/tirages': typeof AuthenticatedFinancesCaissierIdTiragesRoute
  '/residence/portail/caution': typeof AuthenticatedResidencePortailCautionIndexRoute
  '/residence/portail/echeances': typeof AuthenticatedResidencePortailEcheancesIndexRoute
  '/residence/portail/paiements': typeof AuthenticatedResidencePortailPaiementsIndexRoute
  '/rh/pointage/consultation': typeof AuthenticatedRhPointageConsultationIndexRoute
  '/admin/roles/$id/permissions': typeof AuthenticatedAdminRolesIdPermissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/en-cours': typeof AuthenticatedEnCoursRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/rapports/': typeof AuthenticatedRapportsIndexRoute
  '/_authenticated/client/clients/$id': typeof AuthenticatedClientClientsIdRoute
  '/_authenticated/facturation/factures/$id': typeof AuthenticatedFacturationFacturesIdRoute
  '/_authenticated/pressing/commandes/$id': typeof AuthenticatedPressingCommandesIdRoute
  '/_authenticated/rapports/activites/$code': typeof AuthenticatedRapportsActivitesCodeRoute
  '/_authenticated/residence/contrats/$id': typeof AuthenticatedResidenceContratsIdRoute
  '/_authenticated/residence/logements/$id': typeof AuthenticatedResidenceLogementsIdRoute
  '/_authenticated/residence/sejours-courts/$id': typeof AuthenticatedResidenceSejoursCourtsIdRoute
  '/_authenticated/rh/bulletins/$id': typeof AuthenticatedRhBulletinsIdRoute
  '/_authenticated/rh/employes/$id': typeof AuthenticatedRhEmployesIdRoute
  '/_authenticated/salle-fete/reservations/$id': typeof AuthenticatedSalleFeteReservationsIdRoute
  '/_authenticated/admin/journal/': typeof AuthenticatedAdminJournalIndexRoute
  '/_authenticated/admin/parametres/': typeof AuthenticatedAdminParametresIndexRoute
  '/_authenticated/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/admin/sauvegardes/': typeof AuthenticatedAdminSauvegardesIndexRoute
  '/_authenticated/admin/utilisateurs/': typeof AuthenticatedAdminUtilisateursIndexRoute
  '/_authenticated/client/clients/': typeof AuthenticatedClientClientsIndexRoute
  '/_authenticated/facturation/factures/': typeof AuthenticatedFacturationFacturesIndexRoute
  '/_authenticated/facturation/prestations/': typeof AuthenticatedFacturationPrestationsIndexRoute
  '/_authenticated/finances/caisses/': typeof AuthenticatedFinancesCaissesIndexRoute
  '/_authenticated/finances/categories-depenses/': typeof AuthenticatedFinancesCategoriesDepensesIndexRoute
  '/_authenticated/finances/depenses/': typeof AuthenticatedFinancesDepensesIndexRoute
  '/_authenticated/finances/encaissements/': typeof AuthenticatedFinancesEncaissementsIndexRoute
  '/_authenticated/finances/impayes/': typeof AuthenticatedFinancesImpayesIndexRoute
  '/_authenticated/finances/moyens-paiement/': typeof AuthenticatedFinancesMoyensPaiementIndexRoute
  '/_authenticated/finances/revenus-utilisateur/': typeof AuthenticatedFinancesRevenusUtilisateurIndexRoute
  '/_authenticated/finances/tableau-de-bord/': typeof AuthenticatedFinancesTableauDeBordIndexRoute
  '/_authenticated/marchandise/categories-produits/': typeof AuthenticatedMarchandiseCategoriesProduitsIndexRoute
  '/_authenticated/marchandise/mouvements/': typeof AuthenticatedMarchandiseMouvementsIndexRoute
  '/_authenticated/marchandise/produits/': typeof AuthenticatedMarchandiseProduitsIndexRoute
  '/_authenticated/marchandise/statistiques/': typeof AuthenticatedMarchandiseStatistiquesIndexRoute
  '/_authenticated/marchandise/ventes/': typeof AuthenticatedMarchandiseVentesIndexRoute
  '/_authenticated/pressing/commandes/': typeof AuthenticatedPressingCommandesIndexRoute
  '/_authenticated/rapports/financier/': typeof AuthenticatedRapportsFinancierIndexRoute
  '/_authenticated/rapports/rh/': typeof AuthenticatedRapportsRhIndexRoute
  '/_authenticated/rapports/synthese-globale/': typeof AuthenticatedRapportsSyntheseGlobaleIndexRoute
  '/_authenticated/residence/abonnements/': typeof AuthenticatedResidenceAbonnementsIndexRoute
  '/_authenticated/residence/batiments/': typeof AuthenticatedResidenceBatimentsIndexRoute
  '/_authenticated/residence/categories-charges/': typeof AuthenticatedResidenceCategoriesChargesIndexRoute
  '/_authenticated/residence/charges/': typeof AuthenticatedResidenceChargesIndexRoute
  '/_authenticated/residence/contrats/': typeof AuthenticatedResidenceContratsIndexRoute
  '/_authenticated/residence/echeances/': typeof AuthenticatedResidenceEcheancesIndexRoute
  '/_authenticated/residence/logements/': typeof AuthenticatedResidenceLogementsIndexRoute
  '/_authenticated/residence/portail/': typeof AuthenticatedResidencePortailIndexRoute
  '/_authenticated/residence/sejours-courts/': typeof AuthenticatedResidenceSejoursCourtsIndexRoute
  '/_authenticated/restaurant/commandes/': typeof AuthenticatedRestaurantCommandesIndexRoute
  '/_authenticated/restaurant/plats/': typeof AuthenticatedRestaurantPlatsIndexRoute
  '/_authenticated/restaurant/statistiques/': typeof AuthenticatedRestaurantStatistiquesIndexRoute
  '/_authenticated/rh/bulletins/': typeof AuthenticatedRhBulletinsIndexRoute
  '/_authenticated/rh/comptes/': typeof AuthenticatedRhComptesIndexRoute
  '/_authenticated/rh/employes/': typeof AuthenticatedRhEmployesIndexRoute
  '/_authenticated/rh/pointage/': typeof AuthenticatedRhPointageIndexRoute
  '/_authenticated/salle-fete/calendrier/': typeof AuthenticatedSalleFeteCalendrierIndexRoute
  '/_authenticated/salle-fete/reservations/': typeof AuthenticatedSalleFeteReservationsIndexRoute
  '/_authenticated/finances/caisses/$id/dashboard': typeof AuthenticatedFinancesCaissesIdDashboardRoute
  '/_authenticated/finances/caissier/$id/dashboard': typeof AuthenticatedFinancesCaissierIdDashboardRoute
  '/_authenticated/finances/caissier/$id/tirages': typeof AuthenticatedFinancesCaissierIdTiragesRoute
  '/_authenticated/residence/portail/caution/': typeof AuthenticatedResidencePortailCautionIndexRoute
  '/_authenticated/residence/portail/echeances/': typeof AuthenticatedResidencePortailEcheancesIndexRoute
  '/_authenticated/residence/portail/paiements/': typeof AuthenticatedResidencePortailPaiementsIndexRoute
  '/_authenticated/rh/pointage/consultation/': typeof AuthenticatedRhPointageConsultationIndexRoute
  '/_authenticated/admin/roles/$id/permissions/': typeof AuthenticatedAdminRolesIdPermissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/en-cours'
    | '/dashboard/'
    | '/rapports/'
    | '/client/clients/$id'
    | '/facturation/factures/$id'
    | '/pressing/commandes/$id'
    | '/rapports/activites/$code'
    | '/residence/contrats/$id'
    | '/residence/logements/$id'
    | '/residence/sejours-courts/$id'
    | '/rh/bulletins/$id'
    | '/rh/employes/$id'
    | '/salle-fete/reservations/$id'
    | '/admin/journal/'
    | '/admin/parametres/'
    | '/admin/roles/'
    | '/admin/sauvegardes/'
    | '/admin/utilisateurs/'
    | '/client/clients/'
    | '/facturation/factures/'
    | '/facturation/prestations/'
    | '/finances/caisses/'
    | '/finances/categories-depenses/'
    | '/finances/depenses/'
    | '/finances/encaissements/'
    | '/finances/impayes/'
    | '/finances/moyens-paiement/'
    | '/finances/revenus-utilisateur/'
    | '/finances/tableau-de-bord/'
    | '/marchandise/categories-produits/'
    | '/marchandise/mouvements/'
    | '/marchandise/produits/'
    | '/marchandise/statistiques/'
    | '/marchandise/ventes/'
    | '/pressing/commandes/'
    | '/rapports/financier/'
    | '/rapports/rh/'
    | '/rapports/synthese-globale/'
    | '/residence/abonnements/'
    | '/residence/batiments/'
    | '/residence/categories-charges/'
    | '/residence/charges/'
    | '/residence/contrats/'
    | '/residence/echeances/'
    | '/residence/logements/'
    | '/residence/portail/'
    | '/residence/sejours-courts/'
    | '/restaurant/commandes/'
    | '/restaurant/plats/'
    | '/restaurant/statistiques/'
    | '/rh/bulletins/'
    | '/rh/comptes/'
    | '/rh/employes/'
    | '/rh/pointage/'
    | '/salle-fete/calendrier/'
    | '/salle-fete/reservations/'
    | '/finances/caisses/$id/dashboard'
    | '/finances/caissier/$id/dashboard'
    | '/finances/caissier/$id/tirages'
    | '/residence/portail/caution/'
    | '/residence/portail/echeances/'
    | '/residence/portail/paiements/'
    | '/rh/pointage/consultation/'
    | '/admin/roles/$id/permissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/en-cours'
    | '/'
    | '/dashboard'
    | '/rapports'
    | '/client/clients/$id'
    | '/facturation/factures/$id'
    | '/pressing/commandes/$id'
    | '/rapports/activites/$code'
    | '/residence/contrats/$id'
    | '/residence/logements/$id'
    | '/residence/sejours-courts/$id'
    | '/rh/bulletins/$id'
    | '/rh/employes/$id'
    | '/salle-fete/reservations/$id'
    | '/admin/journal'
    | '/admin/parametres'
    | '/admin/roles'
    | '/admin/sauvegardes'
    | '/admin/utilisateurs'
    | '/client/clients'
    | '/facturation/factures'
    | '/facturation/prestations'
    | '/finances/caisses'
    | '/finances/categories-depenses'
    | '/finances/depenses'
    | '/finances/encaissements'
    | '/finances/impayes'
    | '/finances/moyens-paiement'
    | '/finances/revenus-utilisateur'
    | '/finances/tableau-de-bord'
    | '/marchandise/categories-produits'
    | '/marchandise/mouvements'
    | '/marchandise/produits'
    | '/marchandise/statistiques'
    | '/marchandise/ventes'
    | '/pressing/commandes'
    | '/rapports/financier'
    | '/rapports/rh'
    | '/rapports/synthese-globale'
    | '/residence/abonnements'
    | '/residence/batiments'
    | '/residence/categories-charges'
    | '/residence/charges'
    | '/residence/contrats'
    | '/residence/echeances'
    | '/residence/logements'
    | '/residence/portail'
    | '/residence/sejours-courts'
    | '/restaurant/commandes'
    | '/restaurant/plats'
    | '/restaurant/statistiques'
    | '/rh/bulletins'
    | '/rh/comptes'
    | '/rh/employes'
    | '/rh/pointage'
    | '/salle-fete/calendrier'
    | '/salle-fete/reservations'
    | '/finances/caisses/$id/dashboard'
    | '/finances/caissier/$id/dashboard'
    | '/finances/caissier/$id/tirages'
    | '/residence/portail/caution'
    | '/residence/portail/echeances'
    | '/residence/portail/paiements'
    | '/rh/pointage/consultation'
    | '/admin/roles/$id/permissions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/en-cours'
    | '/_authenticated/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/rapports/'
    | '/_authenticated/client/clients/$id'
    | '/_authenticated/facturation/factures/$id'
    | '/_authenticated/pressing/commandes/$id'
    | '/_authenticated/rapports/activites/$code'
    | '/_authenticated/residence/contrats/$id'
    | '/_authenticated/residence/logements/$id'
    | '/_authenticated/residence/sejours-courts/$id'
    | '/_authenticated/rh/bulletins/$id'
    | '/_authenticated/rh/employes/$id'
    | '/_authenticated/salle-fete/reservations/$id'
    | '/_authenticated/admin/journal/'
    | '/_authenticated/admin/parametres/'
    | '/_authenticated/admin/roles/'
    | '/_authenticated/admin/sauvegardes/'
    | '/_authenticated/admin/utilisateurs/'
    | '/_authenticated/client/clients/'
    | '/_authenticated/facturation/factures/'
    | '/_authenticated/facturation/prestations/'
    | '/_authenticated/finances/caisses/'
    | '/_authenticated/finances/categories-depenses/'
    | '/_authenticated/finances/depenses/'
    | '/_authenticated/finances/encaissements/'
    | '/_authenticated/finances/impayes/'
    | '/_authenticated/finances/moyens-paiement/'
    | '/_authenticated/finances/revenus-utilisateur/'
    | '/_authenticated/finances/tableau-de-bord/'
    | '/_authenticated/marchandise/categories-produits/'
    | '/_authenticated/marchandise/mouvements/'
    | '/_authenticated/marchandise/produits/'
    | '/_authenticated/marchandise/statistiques/'
    | '/_authenticated/marchandise/ventes/'
    | '/_authenticated/pressing/commandes/'
    | '/_authenticated/rapports/financier/'
    | '/_authenticated/rapports/rh/'
    | '/_authenticated/rapports/synthese-globale/'
    | '/_authenticated/residence/abonnements/'
    | '/_authenticated/residence/batiments/'
    | '/_authenticated/residence/categories-charges/'
    | '/_authenticated/residence/charges/'
    | '/_authenticated/residence/contrats/'
    | '/_authenticated/residence/echeances/'
    | '/_authenticated/residence/logements/'
    | '/_authenticated/residence/portail/'
    | '/_authenticated/residence/sejours-courts/'
    | '/_authenticated/restaurant/commandes/'
    | '/_authenticated/restaurant/plats/'
    | '/_authenticated/restaurant/statistiques/'
    | '/_authenticated/rh/bulletins/'
    | '/_authenticated/rh/comptes/'
    | '/_authenticated/rh/employes/'
    | '/_authenticated/rh/pointage/'
    | '/_authenticated/salle-fete/calendrier/'
    | '/_authenticated/salle-fete/reservations/'
    | '/_authenticated/finances/caisses/$id/dashboard'
    | '/_authenticated/finances/caissier/$id/dashboard'
    | '/_authenticated/finances/caissier/$id/tirages'
    | '/_authenticated/residence/portail/caution/'
    | '/_authenticated/residence/portail/echeances/'
    | '/_authenticated/residence/portail/paiements/'
    | '/_authenticated/rh/pointage/consultation/'
    | '/_authenticated/admin/roles/$id/permissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/en-cours': {
      id: '/_authenticated/en-cours'
      path: '/en-cours'
      fullPath: '/en-cours'
      preLoaderRoute: typeof AuthenticatedEnCoursRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports/': {
      id: '/_authenticated/rapports/'
      path: '/rapports'
      fullPath: '/rapports/'
      preLoaderRoute: typeof AuthenticatedRapportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/journal/': {
      id: '/_authenticated/admin/journal/'
      path: '/admin/journal'
      fullPath: '/admin/journal/'
      preLoaderRoute: typeof AuthenticatedAdminJournalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/parametres/': {
      id: '/_authenticated/admin/parametres/'
      path: '/admin/parametres'
      fullPath: '/admin/parametres/'
      preLoaderRoute: typeof AuthenticatedAdminParametresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles/': {
      id: '/_authenticated/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/sauvegardes/': {
      id: '/_authenticated/admin/sauvegardes/'
      path: '/admin/sauvegardes'
      fullPath: '/admin/sauvegardes/'
      preLoaderRoute: typeof AuthenticatedAdminSauvegardesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/utilisateurs/': {
      id: '/_authenticated/admin/utilisateurs/'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs/'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/clients/': {
      id: '/_authenticated/client/clients/'
      path: '/client/clients'
      fullPath: '/client/clients/'
      preLoaderRoute: typeof AuthenticatedClientClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/clients/$id': {
      id: '/_authenticated/client/clients/$id'
      path: '/client/clients/$id'
      fullPath: '/client/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientClientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturation/factures/': {
      id: '/_authenticated/facturation/factures/'
      path: '/facturation/factures'
      fullPath: '/facturation/factures/'
      preLoaderRoute: typeof AuthenticatedFacturationFacturesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturation/factures/$id': {
      id: '/_authenticated/facturation/factures/$id'
      path: '/facturation/factures/$id'
      fullPath: '/facturation/factures/$id'
      preLoaderRoute: typeof AuthenticatedFacturationFacturesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturation/prestations/': {
      id: '/_authenticated/facturation/prestations/'
      path: '/facturation/prestations'
      fullPath: '/facturation/prestations/'
      preLoaderRoute: typeof AuthenticatedFacturationPrestationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/caisses/': {
      id: '/_authenticated/finances/caisses/'
      path: '/finances/caisses'
      fullPath: '/finances/caisses/'
      preLoaderRoute: typeof AuthenticatedFinancesCaissesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/categories-depenses/': {
      id: '/_authenticated/finances/categories-depenses/'
      path: '/finances/categories-depenses'
      fullPath: '/finances/categories-depenses/'
      preLoaderRoute: typeof AuthenticatedFinancesCategoriesDepensesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/depenses/': {
      id: '/_authenticated/finances/depenses/'
      path: '/finances/depenses'
      fullPath: '/finances/depenses/'
      preLoaderRoute: typeof AuthenticatedFinancesDepensesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/encaissements/': {
      id: '/_authenticated/finances/encaissements/'
      path: '/finances/encaissements'
      fullPath: '/finances/encaissements/'
      preLoaderRoute: typeof AuthenticatedFinancesEncaissementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/impayes/': {
      id: '/_authenticated/finances/impayes/'
      path: '/finances/impayes'
      fullPath: '/finances/impayes/'
      preLoaderRoute: typeof AuthenticatedFinancesImpayesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/moyens-paiement/': {
      id: '/_authenticated/finances/moyens-paiement/'
      path: '/finances/moyens-paiement'
      fullPath: '/finances/moyens-paiement/'
      preLoaderRoute: typeof AuthenticatedFinancesMoyensPaiementIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/revenus-utilisateur/': {
      id: '/_authenticated/finances/revenus-utilisateur/'
      path: '/finances/revenus-utilisateur'
      fullPath: '/finances/revenus-utilisateur/'
      preLoaderRoute: typeof AuthenticatedFinancesRevenusUtilisateurIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/tableau-de-bord/': {
      id: '/_authenticated/finances/tableau-de-bord/'
      path: '/finances/tableau-de-bord'
      fullPath: '/finances/tableau-de-bord/'
      preLoaderRoute: typeof AuthenticatedFinancesTableauDeBordIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marchandise/categories-produits/': {
      id: '/_authenticated/marchandise/categories-produits/'
      path: '/marchandise/categories-produits'
      fullPath: '/marchandise/categories-produits/'
      preLoaderRoute: typeof AuthenticatedMarchandiseCategoriesProduitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marchandise/mouvements/': {
      id: '/_authenticated/marchandise/mouvements/'
      path: '/marchandise/mouvements'
      fullPath: '/marchandise/mouvements/'
      preLoaderRoute: typeof AuthenticatedMarchandiseMouvementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marchandise/produits/': {
      id: '/_authenticated/marchandise/produits/'
      path: '/marchandise/produits'
      fullPath: '/marchandise/produits/'
      preLoaderRoute: typeof AuthenticatedMarchandiseProduitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marchandise/statistiques/': {
      id: '/_authenticated/marchandise/statistiques/'
      path: '/marchandise/statistiques'
      fullPath: '/marchandise/statistiques/'
      preLoaderRoute: typeof AuthenticatedMarchandiseStatistiquesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marchandise/ventes/': {
      id: '/_authenticated/marchandise/ventes/'
      path: '/marchandise/ventes'
      fullPath: '/marchandise/ventes/'
      preLoaderRoute: typeof AuthenticatedMarchandiseVentesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pressing/commandes/': {
      id: '/_authenticated/pressing/commandes/'
      path: '/pressing/commandes'
      fullPath: '/pressing/commandes/'
      preLoaderRoute: typeof AuthenticatedPressingCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pressing/commandes/$id': {
      id: '/_authenticated/pressing/commandes/$id'
      path: '/pressing/commandes/$id'
      fullPath: '/pressing/commandes/$id'
      preLoaderRoute: typeof AuthenticatedPressingCommandesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports/activites/$code': {
      id: '/_authenticated/rapports/activites/$code'
      path: '/rapports/activites/$code'
      fullPath: '/rapports/activites/$code'
      preLoaderRoute: typeof AuthenticatedRapportsActivitesCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports/financier/': {
      id: '/_authenticated/rapports/financier/'
      path: '/rapports/financier'
      fullPath: '/rapports/financier/'
      preLoaderRoute: typeof AuthenticatedRapportsFinancierIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports/rh/': {
      id: '/_authenticated/rapports/rh/'
      path: '/rapports/rh'
      fullPath: '/rapports/rh/'
      preLoaderRoute: typeof AuthenticatedRapportsRhIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports/synthese-globale/': {
      id: '/_authenticated/rapports/synthese-globale/'
      path: '/rapports/synthese-globale'
      fullPath: '/rapports/synthese-globale/'
      preLoaderRoute: typeof AuthenticatedRapportsSyntheseGlobaleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/abonnements/': {
      id: '/_authenticated/residence/abonnements/'
      path: '/residence/abonnements'
      fullPath: '/residence/abonnements/'
      preLoaderRoute: typeof AuthenticatedResidenceAbonnementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/batiments/': {
      id: '/_authenticated/residence/batiments/'
      path: '/residence/batiments'
      fullPath: '/residence/batiments/'
      preLoaderRoute: typeof AuthenticatedResidenceBatimentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/categories-charges/': {
      id: '/_authenticated/residence/categories-charges/'
      path: '/residence/categories-charges'
      fullPath: '/residence/categories-charges/'
      preLoaderRoute: typeof AuthenticatedResidenceCategoriesChargesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/charges/': {
      id: '/_authenticated/residence/charges/'
      path: '/residence/charges'
      fullPath: '/residence/charges/'
      preLoaderRoute: typeof AuthenticatedResidenceChargesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/contrats/': {
      id: '/_authenticated/residence/contrats/'
      path: '/residence/contrats'
      fullPath: '/residence/contrats/'
      preLoaderRoute: typeof AuthenticatedResidenceContratsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/contrats/$id': {
      id: '/_authenticated/residence/contrats/$id'
      path: '/residence/contrats/$id'
      fullPath: '/residence/contrats/$id'
      preLoaderRoute: typeof AuthenticatedResidenceContratsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/echeances/': {
      id: '/_authenticated/residence/echeances/'
      path: '/residence/echeances'
      fullPath: '/residence/echeances/'
      preLoaderRoute: typeof AuthenticatedResidenceEcheancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/logements/': {
      id: '/_authenticated/residence/logements/'
      path: '/residence/logements'
      fullPath: '/residence/logements/'
      preLoaderRoute: typeof AuthenticatedResidenceLogementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/logements/$id': {
      id: '/_authenticated/residence/logements/$id'
      path: '/residence/logements/$id'
      fullPath: '/residence/logements/$id'
      preLoaderRoute: typeof AuthenticatedResidenceLogementsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/portail/': {
      id: '/_authenticated/residence/portail/'
      path: '/residence/portail'
      fullPath: '/residence/portail/'
      preLoaderRoute: typeof AuthenticatedResidencePortailIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/sejours-courts/': {
      id: '/_authenticated/residence/sejours-courts/'
      path: '/residence/sejours-courts'
      fullPath: '/residence/sejours-courts/'
      preLoaderRoute: typeof AuthenticatedResidenceSejoursCourtsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/sejours-courts/$id': {
      id: '/_authenticated/residence/sejours-courts/$id'
      path: '/residence/sejours-courts/$id'
      fullPath: '/residence/sejours-courts/$id'
      preLoaderRoute: typeof AuthenticatedResidenceSejoursCourtsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/restaurant/commandes/': {
      id: '/_authenticated/restaurant/commandes/'
      path: '/restaurant/commandes'
      fullPath: '/restaurant/commandes/'
      preLoaderRoute: typeof AuthenticatedRestaurantCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/restaurant/plats/': {
      id: '/_authenticated/restaurant/plats/'
      path: '/restaurant/plats'
      fullPath: '/restaurant/plats/'
      preLoaderRoute: typeof AuthenticatedRestaurantPlatsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/restaurant/statistiques/': {
      id: '/_authenticated/restaurant/statistiques/'
      path: '/restaurant/statistiques'
      fullPath: '/restaurant/statistiques/'
      preLoaderRoute: typeof AuthenticatedRestaurantStatistiquesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh/bulletins/': {
      id: '/_authenticated/rh/bulletins/'
      path: '/rh/bulletins'
      fullPath: '/rh/bulletins/'
      preLoaderRoute: typeof AuthenticatedRhBulletinsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh/bulletins/$id': {
      id: '/_authenticated/rh/bulletins/$id'
      path: '/rh/bulletins/$id'
      fullPath: '/rh/bulletins/$id'
      preLoaderRoute: typeof AuthenticatedRhBulletinsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh/comptes/': {
      id: '/_authenticated/rh/comptes/'
      path: '/rh/comptes'
      fullPath: '/rh/comptes/'
      preLoaderRoute: typeof AuthenticatedRhComptesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh/employes/': {
      id: '/_authenticated/rh/employes/'
      path: '/rh/employes'
      fullPath: '/rh/employes/'
      preLoaderRoute: typeof AuthenticatedRhEmployesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh/employes/$id': {
      id: '/_authenticated/rh/employes/$id'
      path: '/rh/employes/$id'
      fullPath: '/rh/employes/$id'
      preLoaderRoute: typeof AuthenticatedRhEmployesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh/pointage/': {
      id: '/_authenticated/rh/pointage/'
      path: '/rh/pointage'
      fullPath: '/rh/pointage/'
      preLoaderRoute: typeof AuthenticatedRhPointageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salle-fete/calendrier/': {
      id: '/_authenticated/salle-fete/calendrier/'
      path: '/salle-fete/calendrier'
      fullPath: '/salle-fete/calendrier/'
      preLoaderRoute: typeof AuthenticatedSalleFeteCalendrierIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salle-fete/reservations/': {
      id: '/_authenticated/salle-fete/reservations/'
      path: '/salle-fete/reservations'
      fullPath: '/salle-fete/reservations/'
      preLoaderRoute: typeof AuthenticatedSalleFeteReservationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salle-fete/reservations/$id': {
      id: '/_authenticated/salle-fete/reservations/$id'
      path: '/salle-fete/reservations/$id'
      fullPath: '/salle-fete/reservations/$id'
      preLoaderRoute: typeof AuthenticatedSalleFeteReservationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/caisses/$id/dashboard': {
      id: '/_authenticated/finances/caisses/$id/dashboard'
      path: '/finances/caisses/$id/dashboard'
      fullPath: '/finances/caisses/$id/dashboard'
      preLoaderRoute: typeof AuthenticatedFinancesCaissesIdDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/caissier/$id/dashboard': {
      id: '/_authenticated/finances/caissier/$id/dashboard'
      path: '/finances/caissier/$id/dashboard'
      fullPath: '/finances/caissier/$id/dashboard'
      preLoaderRoute: typeof AuthenticatedFinancesCaissierIdDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/caissier/$id/tirages': {
      id: '/_authenticated/finances/caissier/$id/tirages'
      path: '/finances/caissier/$id/tirages'
      fullPath: '/finances/caissier/$id/tirages'
      preLoaderRoute: typeof AuthenticatedFinancesCaissierIdTiragesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/portail/caution/': {
      id: '/_authenticated/residence/portail/caution/'
      path: '/residence/portail/caution'
      fullPath: '/residence/portail/caution/'
      preLoaderRoute: typeof AuthenticatedResidencePortailCautionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/portail/echeances/': {
      id: '/_authenticated/residence/portail/echeances/'
      path: '/residence/portail/echeances'
      fullPath: '/residence/portail/echeances/'
      preLoaderRoute: typeof AuthenticatedResidencePortailEcheancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residence/portail/paiements/': {
      id: '/_authenticated/residence/portail/paiements/'
      path: '/residence/portail/paiements'
      fullPath: '/residence/portail/paiements/'
      preLoaderRoute: typeof AuthenticatedResidencePortailPaiementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh/pointage/consultation/': {
      id: '/_authenticated/rh/pointage/consultation/'
      path: '/rh/pointage/consultation'
      fullPath: '/rh/pointage/consultation/'
      preLoaderRoute: typeof AuthenticatedRhPointageConsultationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles/$id/permissions/': {
      id: '/_authenticated/admin/roles/$id/permissions/'
      path: '/admin/roles/$id/permissions'
      fullPath: '/admin/roles/$id/permissions/'
      preLoaderRoute: typeof AuthenticatedAdminRolesIdPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEnCoursRoute: typeof AuthenticatedEnCoursRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedRapportsIndexRoute: typeof AuthenticatedRapportsIndexRoute
  AuthenticatedClientClientsIdRoute: typeof AuthenticatedClientClientsIdRoute
  AuthenticatedFacturationFacturesIdRoute: typeof AuthenticatedFacturationFacturesIdRoute
  AuthenticatedPressingCommandesIdRoute: typeof AuthenticatedPressingCommandesIdRoute
  AuthenticatedRapportsActivitesCodeRoute: typeof AuthenticatedRapportsActivitesCodeRoute
  AuthenticatedResidenceContratsIdRoute: typeof AuthenticatedResidenceContratsIdRoute
  AuthenticatedResidenceLogementsIdRoute: typeof AuthenticatedResidenceLogementsIdRoute
  AuthenticatedResidenceSejoursCourtsIdRoute: typeof AuthenticatedResidenceSejoursCourtsIdRoute
  AuthenticatedRhBulletinsIdRoute: typeof AuthenticatedRhBulletinsIdRoute
  AuthenticatedRhEmployesIdRoute: typeof AuthenticatedRhEmployesIdRoute
  AuthenticatedSalleFeteReservationsIdRoute: typeof AuthenticatedSalleFeteReservationsIdRoute
  AuthenticatedAdminJournalIndexRoute: typeof AuthenticatedAdminJournalIndexRoute
  AuthenticatedAdminParametresIndexRoute: typeof AuthenticatedAdminParametresIndexRoute
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
  AuthenticatedAdminSauvegardesIndexRoute: typeof AuthenticatedAdminSauvegardesIndexRoute
  AuthenticatedAdminUtilisateursIndexRoute: typeof AuthenticatedAdminUtilisateursIndexRoute
  AuthenticatedClientClientsIndexRoute: typeof AuthenticatedClientClientsIndexRoute
  AuthenticatedFacturationFacturesIndexRoute: typeof AuthenticatedFacturationFacturesIndexRoute
  AuthenticatedFacturationPrestationsIndexRoute: typeof AuthenticatedFacturationPrestationsIndexRoute
  AuthenticatedFinancesCaissesIndexRoute: typeof AuthenticatedFinancesCaissesIndexRoute
  AuthenticatedFinancesCategoriesDepensesIndexRoute: typeof AuthenticatedFinancesCategoriesDepensesIndexRoute
  AuthenticatedFinancesDepensesIndexRoute: typeof AuthenticatedFinancesDepensesIndexRoute
  AuthenticatedFinancesEncaissementsIndexRoute: typeof AuthenticatedFinancesEncaissementsIndexRoute
  AuthenticatedFinancesImpayesIndexRoute: typeof AuthenticatedFinancesImpayesIndexRoute
  AuthenticatedFinancesMoyensPaiementIndexRoute: typeof AuthenticatedFinancesMoyensPaiementIndexRoute
  AuthenticatedFinancesRevenusUtilisateurIndexRoute: typeof AuthenticatedFinancesRevenusUtilisateurIndexRoute
  AuthenticatedFinancesTableauDeBordIndexRoute: typeof AuthenticatedFinancesTableauDeBordIndexRoute
  AuthenticatedMarchandiseCategoriesProduitsIndexRoute: typeof AuthenticatedMarchandiseCategoriesProduitsIndexRoute
  AuthenticatedMarchandiseMouvementsIndexRoute: typeof AuthenticatedMarchandiseMouvementsIndexRoute
  AuthenticatedMarchandiseProduitsIndexRoute: typeof AuthenticatedMarchandiseProduitsIndexRoute
  AuthenticatedMarchandiseStatistiquesIndexRoute: typeof AuthenticatedMarchandiseStatistiquesIndexRoute
  AuthenticatedMarchandiseVentesIndexRoute: typeof AuthenticatedMarchandiseVentesIndexRoute
  AuthenticatedPressingCommandesIndexRoute: typeof AuthenticatedPressingCommandesIndexRoute
  AuthenticatedRapportsFinancierIndexRoute: typeof AuthenticatedRapportsFinancierIndexRoute
  AuthenticatedRapportsRhIndexRoute: typeof AuthenticatedRapportsRhIndexRoute
  AuthenticatedRapportsSyntheseGlobaleIndexRoute: typeof AuthenticatedRapportsSyntheseGlobaleIndexRoute
  AuthenticatedResidenceAbonnementsIndexRoute: typeof AuthenticatedResidenceAbonnementsIndexRoute
  AuthenticatedResidenceBatimentsIndexRoute: typeof AuthenticatedResidenceBatimentsIndexRoute
  AuthenticatedResidenceCategoriesChargesIndexRoute: typeof AuthenticatedResidenceCategoriesChargesIndexRoute
  AuthenticatedResidenceChargesIndexRoute: typeof AuthenticatedResidenceChargesIndexRoute
  AuthenticatedResidenceContratsIndexRoute: typeof AuthenticatedResidenceContratsIndexRoute
  AuthenticatedResidenceEcheancesIndexRoute: typeof AuthenticatedResidenceEcheancesIndexRoute
  AuthenticatedResidenceLogementsIndexRoute: typeof AuthenticatedResidenceLogementsIndexRoute
  AuthenticatedResidencePortailIndexRoute: typeof AuthenticatedResidencePortailIndexRoute
  AuthenticatedResidenceSejoursCourtsIndexRoute: typeof AuthenticatedResidenceSejoursCourtsIndexRoute
  AuthenticatedRestaurantCommandesIndexRoute: typeof AuthenticatedRestaurantCommandesIndexRoute
  AuthenticatedRestaurantPlatsIndexRoute: typeof AuthenticatedRestaurantPlatsIndexRoute
  AuthenticatedRestaurantStatistiquesIndexRoute: typeof AuthenticatedRestaurantStatistiquesIndexRoute
  AuthenticatedRhBulletinsIndexRoute: typeof AuthenticatedRhBulletinsIndexRoute
  AuthenticatedRhComptesIndexRoute: typeof AuthenticatedRhComptesIndexRoute
  AuthenticatedRhEmployesIndexRoute: typeof AuthenticatedRhEmployesIndexRoute
  AuthenticatedRhPointageIndexRoute: typeof AuthenticatedRhPointageIndexRoute
  AuthenticatedSalleFeteCalendrierIndexRoute: typeof AuthenticatedSalleFeteCalendrierIndexRoute
  AuthenticatedSalleFeteReservationsIndexRoute: typeof AuthenticatedSalleFeteReservationsIndexRoute
  AuthenticatedFinancesCaissesIdDashboardRoute: typeof AuthenticatedFinancesCaissesIdDashboardRoute
  AuthenticatedFinancesCaissierIdDashboardRoute: typeof AuthenticatedFinancesCaissierIdDashboardRoute
  AuthenticatedFinancesCaissierIdTiragesRoute: typeof AuthenticatedFinancesCaissierIdTiragesRoute
  AuthenticatedResidencePortailCautionIndexRoute: typeof AuthenticatedResidencePortailCautionIndexRoute
  AuthenticatedResidencePortailEcheancesIndexRoute: typeof AuthenticatedResidencePortailEcheancesIndexRoute
  AuthenticatedResidencePortailPaiementsIndexRoute: typeof AuthenticatedResidencePortailPaiementsIndexRoute
  AuthenticatedRhPointageConsultationIndexRoute: typeof AuthenticatedRhPointageConsultationIndexRoute
  AuthenticatedAdminRolesIdPermissionsIndexRoute: typeof AuthenticatedAdminRolesIdPermissionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEnCoursRoute: AuthenticatedEnCoursRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedRapportsIndexRoute: AuthenticatedRapportsIndexRoute,
  AuthenticatedClientClientsIdRoute: AuthenticatedClientClientsIdRoute,
  AuthenticatedFacturationFacturesIdRoute:
    AuthenticatedFacturationFacturesIdRoute,
  AuthenticatedPressingCommandesIdRoute: AuthenticatedPressingCommandesIdRoute,
  AuthenticatedRapportsActivitesCodeRoute:
    AuthenticatedRapportsActivitesCodeRoute,
  AuthenticatedResidenceContratsIdRoute: AuthenticatedResidenceContratsIdRoute,
  AuthenticatedResidenceLogementsIdRoute:
    AuthenticatedResidenceLogementsIdRoute,
  AuthenticatedResidenceSejoursCourtsIdRoute:
    AuthenticatedResidenceSejoursCourtsIdRoute,
  AuthenticatedRhBulletinsIdRoute: AuthenticatedRhBulletinsIdRoute,
  AuthenticatedRhEmployesIdRoute: AuthenticatedRhEmployesIdRoute,
  AuthenticatedSalleFeteReservationsIdRoute:
    AuthenticatedSalleFeteReservationsIdRoute,
  AuthenticatedAdminJournalIndexRoute: AuthenticatedAdminJournalIndexRoute,
  AuthenticatedAdminParametresIndexRoute:
    AuthenticatedAdminParametresIndexRoute,
  AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
  AuthenticatedAdminSauvegardesIndexRoute:
    AuthenticatedAdminSauvegardesIndexRoute,
  AuthenticatedAdminUtilisateursIndexRoute:
    AuthenticatedAdminUtilisateursIndexRoute,
  AuthenticatedClientClientsIndexRoute: AuthenticatedClientClientsIndexRoute,
  AuthenticatedFacturationFacturesIndexRoute:
    AuthenticatedFacturationFacturesIndexRoute,
  AuthenticatedFacturationPrestationsIndexRoute:
    AuthenticatedFacturationPrestationsIndexRoute,
  AuthenticatedFinancesCaissesIndexRoute:
    AuthenticatedFinancesCaissesIndexRoute,
  AuthenticatedFinancesCategoriesDepensesIndexRoute:
    AuthenticatedFinancesCategoriesDepensesIndexRoute,
  AuthenticatedFinancesDepensesIndexRoute:
    AuthenticatedFinancesDepensesIndexRoute,
  AuthenticatedFinancesEncaissementsIndexRoute:
    AuthenticatedFinancesEncaissementsIndexRoute,
  AuthenticatedFinancesImpayesIndexRoute:
    AuthenticatedFinancesImpayesIndexRoute,
  AuthenticatedFinancesMoyensPaiementIndexRoute:
    AuthenticatedFinancesMoyensPaiementIndexRoute,
  AuthenticatedFinancesRevenusUtilisateurIndexRoute:
    AuthenticatedFinancesRevenusUtilisateurIndexRoute,
  AuthenticatedFinancesTableauDeBordIndexRoute:
    AuthenticatedFinancesTableauDeBordIndexRoute,
  AuthenticatedMarchandiseCategoriesProduitsIndexRoute:
    AuthenticatedMarchandiseCategoriesProduitsIndexRoute,
  AuthenticatedMarchandiseMouvementsIndexRoute:
    AuthenticatedMarchandiseMouvementsIndexRoute,
  AuthenticatedMarchandiseProduitsIndexRoute:
    AuthenticatedMarchandiseProduitsIndexRoute,
  AuthenticatedMarchandiseStatistiquesIndexRoute:
    AuthenticatedMarchandiseStatistiquesIndexRoute,
  AuthenticatedMarchandiseVentesIndexRoute:
    AuthenticatedMarchandiseVentesIndexRoute,
  AuthenticatedPressingCommandesIndexRoute:
    AuthenticatedPressingCommandesIndexRoute,
  AuthenticatedRapportsFinancierIndexRoute:
    AuthenticatedRapportsFinancierIndexRoute,
  AuthenticatedRapportsRhIndexRoute: AuthenticatedRapportsRhIndexRoute,
  AuthenticatedRapportsSyntheseGlobaleIndexRoute:
    AuthenticatedRapportsSyntheseGlobaleIndexRoute,
  AuthenticatedResidenceAbonnementsIndexRoute:
    AuthenticatedResidenceAbonnementsIndexRoute,
  AuthenticatedResidenceBatimentsIndexRoute:
    AuthenticatedResidenceBatimentsIndexRoute,
  AuthenticatedResidenceCategoriesChargesIndexRoute:
    AuthenticatedResidenceCategoriesChargesIndexRoute,
  AuthenticatedResidenceChargesIndexRoute:
    AuthenticatedResidenceChargesIndexRoute,
  AuthenticatedResidenceContratsIndexRoute:
    AuthenticatedResidenceContratsIndexRoute,
  AuthenticatedResidenceEcheancesIndexRoute:
    AuthenticatedResidenceEcheancesIndexRoute,
  AuthenticatedResidenceLogementsIndexRoute:
    AuthenticatedResidenceLogementsIndexRoute,
  AuthenticatedResidencePortailIndexRoute:
    AuthenticatedResidencePortailIndexRoute,
  AuthenticatedResidenceSejoursCourtsIndexRoute:
    AuthenticatedResidenceSejoursCourtsIndexRoute,
  AuthenticatedRestaurantCommandesIndexRoute:
    AuthenticatedRestaurantCommandesIndexRoute,
  AuthenticatedRestaurantPlatsIndexRoute:
    AuthenticatedRestaurantPlatsIndexRoute,
  AuthenticatedRestaurantStatistiquesIndexRoute:
    AuthenticatedRestaurantStatistiquesIndexRoute,
  AuthenticatedRhBulletinsIndexRoute: AuthenticatedRhBulletinsIndexRoute,
  AuthenticatedRhComptesIndexRoute: AuthenticatedRhComptesIndexRoute,
  AuthenticatedRhEmployesIndexRoute: AuthenticatedRhEmployesIndexRoute,
  AuthenticatedRhPointageIndexRoute: AuthenticatedRhPointageIndexRoute,
  AuthenticatedSalleFeteCalendrierIndexRoute:
    AuthenticatedSalleFeteCalendrierIndexRoute,
  AuthenticatedSalleFeteReservationsIndexRoute:
    AuthenticatedSalleFeteReservationsIndexRoute,
  AuthenticatedFinancesCaissesIdDashboardRoute:
    AuthenticatedFinancesCaissesIdDashboardRoute,
  AuthenticatedFinancesCaissierIdDashboardRoute:
    AuthenticatedFinancesCaissierIdDashboardRoute,
  AuthenticatedFinancesCaissierIdTiragesRoute:
    AuthenticatedFinancesCaissierIdTiragesRoute,
  AuthenticatedResidencePortailCautionIndexRoute:
    AuthenticatedResidencePortailCautionIndexRoute,
  AuthenticatedResidencePortailEcheancesIndexRoute:
    AuthenticatedResidencePortailEcheancesIndexRoute,
  AuthenticatedResidencePortailPaiementsIndexRoute:
    AuthenticatedResidencePortailPaiementsIndexRoute,
  AuthenticatedRhPointageConsultationIndexRoute:
    AuthenticatedRhPointageConsultationIndexRoute,
  AuthenticatedAdminRolesIdPermissionsIndexRoute:
    AuthenticatedAdminRolesIdPermissionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
